@props(['previews' => [], 'active' => 'invitation'])
@php
    $labels = [
        'invitation' => 'RFQ invitation',
        'reminder' => 'Due-date reminder',
        'received' => 'Quote received',
        'award' => 'Supplier award',
        'not_selected' => 'Not selected',
    ];
@endphp
<div class="ft-rfq-preview-backdrop" wire:click.self="closeRfqEmailPreview">
    <section class="ft-rfq-preview-modal" role="dialog" aria-modal="true" aria-label="Automated supplier email previews">
        <header><div><h2>Automated supplier emails</h2><p>Preview the messages generated by the inquiry and award workflow.</p></div><button type="button" wire:click="closeRfqEmailPreview" aria-label="Close">×</button></header>
        <div class="ft-rfq-preview-body">
            <nav>
                @foreach($labels as $key => $label)
                    <button type="button" class="{{ $active === $key ? 'active' : '' }}" wire:click="setRfqEmailPreviewType('{{ $key }}')">{{ $label }}</button>
                @endforeach
            </nav>
            <div class="ft-rfq-preview-frame-wrap">
                <iframe title="{{ $labels[$active] ?? 'Email preview' }}" srcdoc="{{ $previews[$active] ?? '' }}"></iframe>
            </div>
        </div>
    </section>
</div>
