<?php $attributes ??= new \Illuminate\View\ComponentAttributeBag;

$__newAttributes = [];
$__propNames = \Illuminate\View\ComponentAttributeBag::extractPropNames((['previews' => [], 'active' => 'invitation']));

foreach ($attributes->all() as $__key => $__value) {
    if (in_array($__key, $__propNames)) {
        $$__key = $$__key ?? $__value;
    } else {
        $__newAttributes[$__key] = $__value;
    }
}

$attributes = new \Illuminate\View\ComponentAttributeBag($__newAttributes);

unset($__propNames);
unset($__newAttributes);

foreach (array_filter((['previews' => [], 'active' => 'invitation']), 'is_string', ARRAY_FILTER_USE_KEY) as $__key => $__value) {
    $$__key = $$__key ?? $__value;
}

$__defined_vars = get_defined_vars();

foreach ($attributes->all() as $__key => $__value) {
    if (array_key_exists($__key, $__defined_vars)) unset($$__key);
}

unset($__defined_vars, $__key, $__value); ?>
<?php
    $labels = [
        'invitation' => 'RFQ invitation',
        'reminder' => 'Due-date reminder',
        'received' => 'Quote received',
        'award' => 'Supplier award',
        'not_selected' => 'Not selected',
    ];
?>
<div class="ft-rfq-preview-backdrop" wire:click.self="closeRfqEmailPreview">
    <section class="ft-rfq-preview-modal" role="dialog" aria-modal="true" aria-label="Automated supplier email previews">
        <header><div><h2>Automated supplier emails</h2><p>Preview the messages generated by the inquiry and award workflow.</p></div><button type="button" wire:click="closeRfqEmailPreview" aria-label="Close">×</button></header>
        <div class="ft-rfq-preview-body">
            <nav>
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $labels; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
                    <button type="button" class="<?php echo e($active === $key ? 'active' : ''); ?>" wire:click="setRfqEmailPreviewType('<?php echo e($key); ?>')"><?php echo e($label); ?></button>
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
            </nav>
            <div class="ft-rfq-preview-frame-wrap">
                <iframe title="<?php echo e($labels[$active] ?? 'Email preview'); ?>" srcdoc="<?php echo e($previews[$active] ?? ''); ?>"></iframe>
            </div>
        </div>
    </section>
</div>
<?php /**PATH /Applications/XAMPP/xamppfiles/htdocs/laravel/flowtrack/resources/views/components/inquiries-rfq-email-preview.blade.php ENDPATH**/ ?>