@php
    $supplier = $supplierDetail;
    $products = collect($supplierDetailProducts);
@endphp

<div class="ft-supplier-create-page ft-supplier-edit-page" data-ft-feedback-scope="form">
    <div class="ft-supplier-create-breadcrumb" aria-label="Breadcrumb">
        <a href="{{ route('master-data', ['group' => 'supplier']) }}" wire:navigate>Suppliers</a>
        <span>/</span>
        <a href="{{ route('master-data', ['group' => 'supplier', 'supplier' => $supplier->id]) }}" wire:navigate>{{ $supplier->name }}</a>
        <span>/</span>
        <strong>Edit</strong>
    </div>

    <header class="ft-supplier-create-head ft-supplier-edit-head">
        <div>
            <h1>Edit supplier</h1>
            <p>Update supplier contact information and availability without changing existing product links.</p>
        </div>
        <x-suppliers.status-badge :status="$supplierEditStatus" />
    </header>

    <div class="ft-supplier-create-layout">
        <div class="ft-supplier-create-main">
            <x-suppliers.form-card title="Supplier information" copy="Keep the supplier name and contact information current.">
                <div class="ft-supplier-form-grid">
                    <x-suppliers.field label="Supplier name" required error="name" wide>
                        <input wire:model.blur="name" type="text" placeholder="Supplier name" autocomplete="organization">
                    </x-suppliers.field>

                    <x-suppliers.field label="Supplier reference" help="The reference is generated by FlowTrack and cannot be changed.">
                        <input type="text" value="{{ $supplier->code }}" disabled readonly>
                    </x-suppliers.field>

                    <x-suppliers.field label="Status" error="supplierEditStatus">
                        <select wire:model="supplierEditStatus">
                            <option value="active">Active</option>
                            <option value="inactive">Inactive</option>
                        </select>
                    </x-suppliers.field>

                    <x-suppliers.field label="Contact person" error="supplierEditContactPerson">
                        <input wire:model.blur="supplierEditContactPerson" type="text" placeholder="Full name" autocomplete="name">
                    </x-suppliers.field>

                    <x-suppliers.field label="Email" error="supplierEditEmail">
                        <input wire:model.blur="supplierEditEmail" type="email" placeholder="name@company.com" autocomplete="email">
                    </x-suppliers.field>

                    <x-suppliers.field label="Phone" error="supplierEditPhone" wide>
                        <input wire:model.blur="supplierEditPhone" type="tel" placeholder="Country code + number" autocomplete="tel">
                    </x-suppliers.field>
                </div>
            </x-suppliers.form-card>

            <x-suppliers.form-card
                title="Assigned products"
                :badge="number_format($products->count()).' linked'"
                copy="Product relationships are managed from the Product catalogue so supplier editing never removes an existing link accidentally."
            >
                @if($products->isEmpty())
                    <div class="ft-supplier-edit-products-empty">No products are currently assigned to this supplier.</div>
                @else
                    <div class="ft-supplier-edit-product-tags">
                        @foreach($products->take(12) as $product)
                            <a href="{{ route('master-data', ['group' => 'product', 'open' => $product->id]) }}" wire:navigate>
                                <strong>{{ $product->productDisplayCode() }}</strong>
                                <span>{{ $product->name }}</span>
                            </a>
                        @endforeach
                        @if($products->count() > 12)
                            <span class="ft-supplier-edit-product-more">+{{ $products->count() - 12 }} more</span>
                        @endif
                    </div>
                @endif

                @if(auth()->user()->canModule('catalog_products', 'view'))
                    <div class="ft-supplier-edit-product-action">
                        <a href="{{ route('master-data', ['group' => 'product', 'supplier_id' => $supplier->id]) }}" wire:navigate class="ft-supplier-list-button is-secondary">
                            Manage assigned products
                        </a>
                    </div>
                @endif
            </x-suppliers.form-card>

            <div class="ft-supplier-create-actions">
                <button type="button" class="ft-supplier-secondary-button" wire:click="cancelSupplierEdit">Cancel</button>
                <button
                    type="button"
                    class="ft-supplier-primary-button"
                    wire:click="saveSupplier"
                    wire:loading.attr="disabled"
                    wire:target="saveSupplier"
                >
                    <span wire:loading.remove wire:target="saveSupplier">Save changes</span>
                    <span wire:loading wire:target="saveSupplier">Saving…</span>
                </button>
            </div>
        </div>
    </div>
</div>
