<?php

namespace App\Support;

final class ArtworkDocumentName
{
    /**
     * Build the persisted/display filename used for Artwork revisions.
     *
     * The version is part of Document::name (before the extension), so every
     * consumer of the document name - task views, Document Archive, emails and
     * downloads - receives the same versioned filename without extra queries or
     * view-specific labels.
     */
    public static function versioned(string $name, int $version, ?string $extensionSource = null): string
    {
        $name = trim(basename($name));
        $version = max(1, $version);

        $nameExtension = (string) pathinfo($name, PATHINFO_EXTENSION);
        $extensionSource = trim((string) ($extensionSource ?? ''));
        $extension = $extensionSource !== ''
            ? (string) pathinfo(basename($extensionSource), PATHINFO_EXTENSION)
            : $nameExtension;
        $stem = $nameExtension !== ''
            ? substr($name, 0, -(strlen($nameExtension) + 1))
            : $name;

        $stem = trim((string) $stem);

        // Remove only suffixes previously generated by FlowTrack. Do not strip
        // ordinary words such as "archive" when they are part of the real name.
        $stem = (string) preg_replace('/\s+-\s+Version\s+\d+\s*$/iu', '', $stem);
        $stem = (string) preg_replace('/(?:\s+-\s+|_)(?:Archive|Archived)\s*$/iu', '', $stem);
        $stem = (string) preg_replace('/\s+\((?:Archive|Archived)\)\s*$/iu', '', $stem);
        $stem = trim($stem);

        if ($stem === '') {
            $stem = 'Artwork';
        }

        return $stem.' - Version '.$version.($extension !== '' ? '.'.$extension : '');
    }

    public static function hasVersion(string $name): bool
    {
        $stem = (string) pathinfo(trim($name), PATHINFO_FILENAME);

        return preg_match('/\s+-\s+Version\s+\d+\s*$/iu', $stem) === 1;
    }
}
